# Generated by Django 4.1.7 on 2023-03-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw57', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
    ]
