# Generated by Django 4.1.7 on 2023-03-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw57', '0003_rename_task_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_types', to='hw57.issue', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_issues', to='hw57.type', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issues', through='hw57.IssueType', to='hw57.type'),
        ),
    ]
